### ISSUE TITLE
Get rid of `xhrStatuses.ABORTED` state

### ISSUE THREAD

**Issue by jamesplease** [jmeas/redux-simple-resource#100]
I'm pretty sure that every time you abort a request, you would rather the status go to NULL rather than ABORTED. The main reason for this is that aborting the request is done by your application, rather than the server.

The consequence of this is that right now there are basically two null states, since ABORTED needs to be checked for in addition to NULL. I've never needed an ABORTED state, and at the risk of being short-sighted, I don't think anyone would need one.

What do others think?

//cc @sprjr @marlonpp

**Comment by whichsteveyp** [comment]
Anything to reduce the API surface area here I am 👍  to doing. I also agree, I don't have too much of a use case for `ABORTED` for my normal apps - usually if you make a request there's not a way to cancel it as I don't stream or upload any large amounts of data - so the request is kind of already...gone.

**Comment by marlonpp** [comment]
Also agree, I think it will be hardly used and removing it will save us another checking.

**Comment by jamesplease** [comment]
Should I also get rid of the `READ_BOOK_ABORT` action types, and recommend just using `READ_BOOK_RESET`?

**Comment by jamesplease** [comment]
Merged in 2.0 branch
