### ISSUE TITLE
Add meta property for additional metadata

### ISSUE THREAD

**Issue by abhisheksoni** [jmeas/redux-simple-resource#102]
Add **meta** property support so that additional metadata for the resources can be passed as part of this property and can ignore having the custom reducer.

**Comment by jamesplease** [comment]
This makes sense to me.

So, like...

```js
{
  type: "READ_MANY_RESOURCES_SUCCEED",
  // Appended to the `resourceListMeta`
  meta: {
    page: 2
  }
}
```

and,

```js
{
  type: "READ_RESOURCE_SUCCEED",
  id: 2,

  // Appended to the individual resource's meta
  meta: {
    hungry: true
  }
}
```

What do you think @sprjr / @marlonpp / @abhisheksoni ?

**Comment by marlonpp** [comment]
Hum, 
Why the additional metadata can't be part of the resource itself? Maybe I missed the point.
In the case of "READ_MANY" the meta would be applied to the collection or for each individual resource?

**Comment by jamesplease** [comment]
> Why the additional metadata can't be part of the resource itself?

I'm not opposed to this, but we'd need a format or system that lets us distinguish between the resource's attributes and its meta. For instance, if we assume a JSON API structure, then `meta` and `attributes` would be top-level props within the resource definition, so you could split them out. simple resource just assumes a flat structure (where everything just goes onto the resource in the store).

 > In the case of "READ_MANY" the meta would be applied to the collection or for each individual resource?

The idea I was thinking is that the meta would be applied to the collection for read many, but I'm open to other ideas!

**Comment by jamesplease** [comment]
Using the same key, `meta`, for both bulk and singular actions could cause an issue if the API moves to an everything-is-bulk system 🤔 .

We can figure that out when the time comes, though.

---

**update**: more importantly, this API makes it hard to do a, say, bulk delete with different meta on each resource. but maybe I just won't support that for now.

---

**update2**: Gonna hold off and add this to 2.0 to prevent adding an API that I immediately break in a big way...

**Comment by jamesplease** [comment]
Gonna close as wontfix. This can be written as a 2.0 plugin to start. We can merge it into core at a later date if we want
