### ISSUE TITLE
Depend on create-redux-constants

### ISSUE THREAD

**Issue by jamesplease** [jmeas/redux-simple-resource#112]
Zero deps is really nice, but @tbranyen's [lib for creating action types](https://github.com/tbranyen/redux-create-action-types) is incredibly useful. I should consider adding this as a dep

**Comment by tbranyen** [comment]
Maybe just in dev? Wrap in a `process.env.NODE_ENV !== 'production'` so consumers don't deal with it in prod.

**Comment by jamesplease** [comment]
are you thinking of a `require()` going in that if statement? or somethin else?

**Comment by jamesplease** [comment]
Closing in favor of https://github.com/jmeas/resourceful-redux/issues/9
