### ISSUE TITLE
Add action types/reducers for more "multi" actions

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-simple-resource#42]
Now that action creators won't be built in, I could go ahead and add `deleteMany`, `updateMany`...etc. as action types and reducer handlers.

I originally didn't do this, since REST doesn't really define a system for multiple writes, so it would have been tricky to do with action creators. But now that action creators are in user land, that's not an issue.

**Comment by jmeas** [comment]
One question I have is the naming convention for these. Right now, we have `READ_ONE_X` for single reads, but we don't have `DELETE_ONE_X`. These should be consistent.

I'm leaning toward:


|Single | Multiple |
|-------|---------|
|READ_BOOK | READ_MANY_BOOKS |
|DELETE_BOOK | DELETE_MANY_BOOKS|
|UPDATE_BOOK| UPDATE_MANY_BOOKS|

and so on.

Thoughts @sprjr ?

**Comment by sprjr** [comment]
I imagine its too confusing to drop the `MANY` portion when pluralizing? I'm wondering if that would be the way to go though if not:

|Single | Multiple |
|-------|---------|
|READ_BOOK | READ_BOOKS |
|DELETE_BOOK | DELETE_BOOKS|
|UPDATE_BOOK| UPDATE_BOOKS|

This would effectively mean we take whatever they give for the resource name and create those action types, and then either use their plural form provided or `name+s` for the multiples.

**Comment by jamesplease** [comment]
Resolved in #108
