### ISSUE TITLE
Naming updates

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-simple-resource#64]
The update utils are currently:

`updateResourcesMeta`
`updateManyResourcesMeta`
`upsertResource`
`upsertManyResources`

Do we want to rename `updateResourcesMeta` to be `updateResourceMeta` since it affects one thing? I'm thinking that we should. @sprjr , what you think? 

---

**Update** Alright, here's my suggestion:

We rename the store properties to be:

`resourceMeta` and `resourceListMeta`. They are currently `resourcesMeta` and `resourcesListMeta`.

Then, we update these functions to be `updateResourceMeta` and `updateManyResourceMetas`

To throw these changes into a chart:

| current | proposed |
|--------|-----------|
| `state.resourcesMeta` | `state.resourceMeta` |
| `state.resourcesListMeta` | `state.resourceListMeta` |
| `updateResourcesMeta()` | `updateResourceMeta()` |
| `updateManyResourcesMeta()` | `updateManyResourceMetas()` |

**Comment by sprjr** [comment]
LGTM, only pluralized one more: `state.resourceListMetas` so it was similar to `updateManyResourceMetas` - what you think?

| current | proposed |
|--------|-----------|
| `state.resourcesMeta` | `state.resourceMeta` |
| `state.resourcesListMeta` | `state.resourceListMetas` |
| `updateResourcesMeta()` | `updateResourceMeta()` |
| `updateManyResourcesMeta()` | `updateManyResourceMetas()` |

**Comment by jmeas** [comment]
:+1:! I'll do it

**Comment by jmeas** [comment]
We decided to go with `resourceListMeta`, since the "list" in this situation is a single "thing" – it's metadata for a single object. That object is the list of other resources.

**Comment by jmeas** [comment]
Resolved in #66
