### ISSUE TITLE
"shorthand" action types

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-simple-resource#85]
Right now, you use the generated action types like `resource.actionTypes.READ_MANY_BOOKS_SUCCEED`. We could just do:

```
resource.actionTypes.readMany
resource.actionTypes.readManyFail
resource.actionTypes.readManySucceed
```

which could possibly be easier to remember? That way, it's the same for all resources. But that could also be confusing since there would be an alias for the action type. 🤔

**Comment by jamesplease** [comment]
Closing in favor of #97
