### ISSUE TITLE
updateManyResourceMetas enhancement

### ISSUE THREAD

**Issue by sprjr** [jmeas/redux-simple-resource#88]
Right now I'm writing this in my actionReducers:
```js
createResource('books', {
  actionReducers: [
    type: customTypes.SELECT_ALL_BOOKS,
    reducer(state) => {
      const {resources, resourceMeta} = state;
      return {
        ...state,
        resourceMeta: updateManyResourceMetas({
          resourceMeta,
          newMeta: {selected: true},
          // ⬇️ ideally I would not have to pass this or look it up
          ids: _.map(resources, request => request.id),
        }),
      };
    }
  ]
}
```

I think we could update the API for this later on to support _not_ passing `ids` and having this apply to all resourceMetas. I guess the caveat would be, would it apply it to all _resourceMetas_ or to all _resources_? Those are slightly different operations.

**Comment by jamesplease** [comment]
Will add this in 1.1

**Comment by jamesplease** [comment]
Actually, not so sure about this. This would require just passing in the list of `resources` (so that the map could be done within the fn), which would make it more confusing to document.

> Either pass in an array of `ids`, or a list of `resources` to apply it to every resource.

'nawm sayin'? What do you think?

**Comment by jamesplease** [comment]
Gonna close as wontfix for now as part of the 1.1 triage. We can keep the convo going though.
