### ISSUE TITLE
Breaking change: renaming meta props

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-simple-resource#92]
What if we made this change:

`resourceMeta` => `meta`
`resourceListMeta` => `listMeta`

I always forget if the meta for the list is `resourceList` or `resourcesList`. Then, I realized it doesn't need to be so complex. These new names contain the same information imo, yet are shorter.

One possible bad thing is that they conflict with the `meta` keys from JSON API. So you'd have:

`slice.resources[2].meta.thing`

as well as...

`slice.meta[2].thing`

😛 

Thoughts?

**Comment by JPorry** [comment]
I like keeping naming simple. In this case it does seem like the word `resource` is a little bit redundant.
And as for the JSON API thing, yeah it is not ideal but I still think that it feels better than `resourceListMeta`

My 2 cents. :)

**Comment by jamesplease** [comment]
Fixed in the 2.0 branch
