### ISSUE TITLE
Deep cloning when passing initial state to createResource

### ISSUE THREAD

**Issue by JPorry** [jmeas/redux-simple-resource#93]
When you pass an initialState to `createResource` it only shallow-copy those values into the initial state that rsr creates for you.
So, if you pass this object

```
{
  resourceListMeta: {
    selected: [],
  }
}
``` 

you will end up losing the default values that were in rsr's default resourceListMeta for that specific resource (`readXhrStatus:'NULL'` &  `createXhrStatus: 'NULL'` for this specific case) 

I can put together a PR for fixing this if it's ok to you.

**Comment by jamesplease** [comment]
This was resolved in #94
